{{- if and (eq .Values.engine.kind "rq") (eq .Values.redis.type "external") (.Values.secrets.externalSecret.enabled) }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.externalSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "docling-serve.fullname" . }}
    component: external-secret
spec:
  refreshInterval: {{ .Values.secrets.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secrets.externalSecret.secretStore.name }}
    kind: {{ .Values.secrets.externalSecret.secretStore.kind }}
  target:
    name: {{ .Values.secrets.rqRedis.name }}
    creationPolicy: Owner
  {{- if .Values.secrets.externalSecret.dataFrom.enabled }}
  dataFrom:
  - extract:
      key: {{ .Values.secrets.externalSecret.remoteSecretName }}
  {{- else }}
  data:
  {{- range .Values.secrets.externalSecret.data }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ $.Values.secrets.externalSecret.remoteSecretName }}
      property: {{ .remoteKey }}
  {{- end }}
  {{- end }}
{{- end }}
