fail_fast: true
repos:
  - repo: local
    hooks:
      - id: client-ruff-format
        name: Ruff formatter
        entry: /bin/zsh -lc 'cd "$(git rev-parse --show-toplevel)/docling-serve-client" && uv run --project . --no-sync ruff format --check --config pyproject.toml docling tests examples'
        pass_filenames: false
        language: system
        always_run: true
      - id: client-ruff
        name: Ruff linter
        entry: /bin/zsh -lc 'cd "$(git rev-parse --show-toplevel)/docling-serve-client" && uv run --project . --no-sync ruff check --fix --config pyproject.toml docling tests examples'
        pass_filenames: false
        language: system
        always_run: true
      - id: client-mypy
        name: MyPy
        entry: /bin/zsh -lc 'cd "$(git rev-parse --show-toplevel)/docling-serve-client" && uv run --project . --no-sync mypy --explicit-package-bases docling'
        pass_filenames: false
        language: system
        always_run: true
      - id: client-uv-lock
        name: uv lock
        entry: /bin/zsh -lc 'cd "$(git rev-parse --show-toplevel)/docling-serve-client" && uv lock --project .'
        pass_filenames: false
        language: system
        always_run: true
