config:
  line-length: false
  no-emphasis-as-header: false
  first-line-heading: false
  MD033:
    allowed_elements: ["details", "summary", "br", "a", "p", "img"]
  MD024:
    siblings_only: true
globs:
  - "**/*.md"
