# AMD ROCm deployment

services:
  docling-serve:
    image: ghcr.io/docling-project/docling-serve-rocm:main
    container_name: docling-serve
    ports:
      - "5001:5001"
    environment:
      DOCLING_SERVE_ENABLE_UI: "true"
      ROCR_VISIBLE_DEVICES: "0" # https://rocm.docs.amd.com/en/latest/conceptual/gpu-isolation.html#rocr-visible-devices
      ## This section is for compatibility with older cards
      # HSA_OVERRIDE_GFX_VERSION: "11.0.0"
      # HSA_ENABLE_SDMA: "0"
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - 44    # video group GID from host
      - 992   # render group GID from host
    restart: always
