name: Dry run docling-serve image building

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_cpu_image:
    name: Build docling-serve "CPU only" container image
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    uses: ./.github/workflows/job-image.yml
    with:
      publish: false
      build_args: |
        UV_SYNC_EXTRA_ARGS=--no-extra cu124
      ghcr_image_name: ds4sd/docling-serve-cpu
      quay_image_name: ""


  build_gpu_image:
    name: Build docling-serve (with GPU support) container image
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    uses: ./.github/workflows/job-image.yml
    with:
      publish: false
      build_args: |
        UV_SYNC_EXTRA_ARGS=--no-extra cpu
      platforms: linux/amd64
      ghcr_image_name: ds4sd/docling-serve
      quay_image_name: ""
