name: Publish docling-serve images

on:
  push:
    branches:
      - main
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_publish_cpu_images:
    name: Push docling-serve "CPU only" container image to GHCR and QUAY
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    secrets: inherit

    uses: ./.github/workflows/job-image.yml
    with:
      publish: true
      environment: registry-creds
      build_args: |
        UV_SYNC_EXTRA_ARGS=--no-extra cu124
      ghcr_image_name: ds4sd/docling-serve-cpu
      quay_image_name: ds4sd/docling-serve-cpu


  build_and_publish_gpu_images:
    name: Push docling-serve (with GPU support) container image to GHCR and QUAY
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    secrets: inherit

    uses: ./.github/workflows/job-image.yml
    with:
      publish: true
      environment: registry-creds
      build_args: |
        UV_SYNC_EXTRA_ARGS=--no-extra cpu
      ghcr_image_name: ds4sd/docling-serve
      quay_image_name: ds4sd/docling-serve

