name: Publish docling-serve images

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

# env:
#   GHCR_REGISTRY: ghcr.io
#   # GHCR_DOCLING_SERVE_CPU_IMAGE_NAME: ds4sd/docling-serve-cpu
#   # GHCR_DOCLING_SERVE_GPU_IMAGE_NAME: ds4sd/docling-serve
#   QUAY_REGISTRY: quay.io
#   # QUAY_DOCLING_SERVE_CPU_IMAGE_NAME: ds4sd/docling-serve-cpu
#   # QUAY_DOCLING_SERVE_GPU_IMAGE_NAME: ds4sd/docling-serve

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_publish_cpu_images:
    name: Push docling-serve "CPU only" container image to GHCR and QUAY
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    secrets: inherit

    uses: ./.github/workflows/job-image.yml
    with:
      publish: true
      environment: registry-creds
      build_args: |
        --build-arg CPU_ONLY=true
      ghcr_image_name: ds4sd/docling-serve-cpu
      quay_image_name: ds4sd/docling-serve-cpu


  build_and_publish_gpu_images:
    name: Push docling-serve (with GPU support) container image to GHCR and QUAY
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    uses: ./.github/workflows/job-image.yml
    with:
      publish: true
      environment: registry-creds
      build_args: |
        --build-arg CPU_ONLY=false
      ghcr_image_name: ds4sd/docling-serve
      quay_image_name: ds4sd/docling-serve

